name: Python application

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install -r dev-requirements.txt
        python3 -m pylint -E *.py
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
    - name: Type checking with mypy
      run: |
        pip install -r dev-requirements.txt
        python3 -m mypy *.py
    - name: Build example Python layer
      run: |
        cd tests/numpy/
        ../../layer-tool.py --list
        ../../layer-tool.py --build awesome-numpy
        du -h awesome-numpy.zip
    - name: Set up Node v10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build example Node.js layer
      run: |
        cd tests/aws-sdk/
        ../../layer-tool.py --list
        ../../layer-tool.py --build awesome-aws-sdk
        du -h awesome-aws-sdk.zip
